// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwxcaetetntlnlfqbkql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3eGNhZXRldG50bG5sZnFia3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTcyMTgsImV4cCI6MjA3MjE5MzIxOH0.5kMHT8t0PadRyJ7DwlqLMfTxcKyS-vBBsn8yMnsMQHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});