// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcxzqtmdkpcapitzqsap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjeHpxdG1ka3BjYXBpdHpxc2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzk1NjEsImV4cCI6MjA2MDYxNTU2MX0.fqA7YkTU3f08IwKmuyN4eXIe0jDtPJ_Qko05fHPGRPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});